#!/bin/bash -eu
# Wait up to 90 seconds for active mass-storage writes to settle before taking
# a snapshot. Success requires observing a write, then seven one-second samples
# below 500 KB/s, or the file-storage process exiting.

PREVWRITTEN=-1

STATE=UNDETERMINED

COUNT=0

BURSTSIZE=0

log "waiting up to 90 seconds for idle interval"
for _ in {1..90}
do
  sleep 1
  PROC=$(pgrep -x file-storage || true)
  if [ -z "$PROC" ]
  then
    log "mass storage process not active, OK to write"
    exit 0
  fi
  WRITTEN=$(grep ^write_bytes "/proc/$PROC/io" | awk '{print $2}')
  if (( PREVWRITTEN == -1 ))
  then
    # Seed the first measurement.
    PREVWRITTEN=$WRITTEN
    continue
  fi
  DELTA=$((WRITTEN-PREVWRITTEN))
  PREVWRITTEN=$WRITTEN

  case $STATE in
    UNDETERMINED)
      if (( DELTA > 500000 ))
      then
        log "write in progress"
        STATE=WRITING
        BURSTSIZE=$DELTA
      else
        true
      fi
      ;;
    WRITING)
      if (( DELTA < 500000 ))
      then
        log "no longer writing, wrote $BURSTSIZE"
        BURSTSIZE=0
        STATE=IDLE
        COUNT=0
      else
        BURSTSIZE=$((BURSTSIZE+DELTA))
      fi
      ;;

    IDLE)
      if (( DELTA > 500000 ))
      then
        # Return to the active-write state.
        log "going back to writing state"
        BURSTSIZE=$DELTA
        STATE=WRITING
        COUNT=0
      else
        COUNT=$((COUNT+1))
        if (( COUNT > 5 ))
        then
          log "no writes seen in the last 5 seconds"
          exit 0
        else
          true
        fi
      fi
      ;;
  esac
done

log "couldn't determine idle interval"
exit 1
